server:
  port: 8080
  servlet:
    context-path: /ssm

#配置mybatis
mybatis:
  #mapper.xml包地址
  mapper-locations: classpath:com/zhaocm/test/mapper/*.xml
  #javaBean类的地址
  type-aliases-package: com.zhaocm.test.po

pagehelper:
  #启用合理化，如果pageNum<1 会查询第一页，如果pageNum >pages 会查询最后一页
  reasonable: true

spring:
  application:
    name: testShiro

  datasource:
    # 如果存在多个数据源，监控的时候可以通过名字来区分
    name: mysql
    url: jdbc:mysql://127.0.0.1:3306/ssm_demo?characterEncoding=utf8&allowMultiQueries=true&useSSL=false&serverTimezone=GMT
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    # 扩展插件
    # 监控统计用的filter:stat 日志用的filter:log4j 防御SQL注入的filter:all
    filter:
      stat:
        merge-sql: true
        slow-sql-millis: 5000
      #3.基础监控配置
      web-stat-filter:
        enabled: true
        url-pattern: /*
    druid:
      # 初始化大小，最小，最大
      min-idle: 5
      initial-size: 5
      max-active: 20
      # 配置获取连接等待超时的时间
      max-wait: 60000
      #配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位毫秒
      time-between-eviction-runs-millis: 60000
      #配置一个连接在池中最小生存时间
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1 FROM user
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      #打开psCache,并且制定每个连接上psCache的大小
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      #配置监控统计拦截的Filter,去掉后监控界面SQL无法统计，wall用于防火墙
      filters: stat,wall,log4j2
      #通过connection-properties属性打开mergerSql功能，慢sql记录
      connection-properties: druid.stat.mergeSql\=true;druid.stat.slowSqlMillis\=5000


#showSql
logging:
  level:
    com.zhaocm.test.mapper: debug


